version: "3"
services:
  mysql-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Qwertyui123!
    ports:
      - 3306:3306
    volumes:
      - ./Docker/database/volume:/var/lib/mysql
      - ./Docker/database/scripts/init.sql:/docker-entrypoint-initdb.d/1.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    